services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: recommendation
      POSTGRES_USER: recommendation
      POSTGRES_PASSWORD: recommendation
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
