-- Criação da tabela de recursos (tb_resources) caso ela não exista
CREATE TABLE IF NOT EXISTS tb_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(255),
    url VARCHAR(255),
    competency_id BIGINT,
    level VARCHAR(255) DEFAULT 'BEGINNER'
);

-- Correção de registros legados: atualiza recursos que possuem o campo level como nulo para 'BEGINNER'
UPDATE tb_resources SET level = 'BEGINNER' WHERE level IS NULL;

-- Criação da tabela de recomendações (tb_recommendations) caso ela não exista
CREATE TABLE IF NOT EXISTS tb_recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    resource_id BIGINT,
    description VARCHAR(255),
    CONSTRAINT fk_recommendation_resource FOREIGN KEY (resource_id) REFERENCES tb_resources(id)
);

-- Adição da constraint de unicidade para evitar duplicações de recomendação para o mesmo usuário e recurso
ALTER TABLE tb_recommendations DROP CONSTRAINT IF EXISTS uk_user_resource;
ALTER TABLE tb_recommendations ADD CONSTRAINT uk_user_resource UNIQUE (user_id, resource_id);
